language: java
sudo: required

before_install:
  - sudo apt-get -y install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar

script: 
  - jdk_switcher use openjdk8
  - mvn clean package

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - mvn clean test jacoco:report coveralls:report
